-- MySQL Script generated by MySQL Workbench
-- Sat Sep 26 20:36:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema luxury_car_rental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema luxury_car_rental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `luxury_car_rental` DEFAULT CHARACTER SET utf8 ;
USE `luxury_car_rental` ;

-- -----------------------------------------------------
-- Table `luxury_car_rental`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxury_car_rental`.`CUSTOMER` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(25) NOT NULL,
  `LicenseNumber` VARCHAR(50) NOT NULL,
  `LicenseIssuer` VARCHAR(100) NOT NULL,
  `LicenseExpirationDate` DATE NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luxury_car_rental`.`VEHICLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxury_car_rental`.`VEHICLE` (
  `VehicleID` INT NOT NULL AUTO_INCREMENT,
  `VIN` CHAR(17) NOT NULL,
  `Make` VARCHAR(50) NOT NULL,
  `Model` VARCHAR(80) NOT NULL,
  `ModelYear` SMALLINT NOT NULL,
  `CurrentDailyRate` DECIMAL(10,2) NOT NULL,
  `ServiceStatus` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VehicleID`),
  UNIQUE INDEX `VIN_UNIQUE` (`VIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luxury_car_rental`.`RESERVATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxury_car_rental`.`RESERVATION` (
  `ReservationID` INT NOT NULL AUTO_INCREMENT,
  `CustomerID` INT NOT NULL,
  `VehicleID` INT NOT NULL,
  `ScheduledPickup` DATETIME NOT NULL,
  `ScheduledReturn` DATETIME NOT NULL,
  `AgreedDailyRate` DECIMAL(10,2) NOT NULL,
  `RequiredDepositAmount` DECIMAL(10,2) NOT NULL,
  `ReservationStatus` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ReservationID`),
  INDEX `fk_reservation_customer_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_reservation_vehicle_idx` (`VehicleID` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `luxury_car_rental`.`CUSTOMER` (`CustomerID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_reservation_vehicle`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `luxury_car_rental`.`VEHICLE` (`VehicleID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luxury_car_rental`.`RENTAL_AGREEMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxury_car_rental`.`RENTAL_AGREEMENT` (
  `RentalID` INT NOT NULL AUTO_INCREMENT,
  `ReservationID` INT NOT NULL,
  `ActualPickup` DATETIME NOT NULL,
  `OdometerOut` INT NOT NULL,
  `ActualReturn` DATETIME NULL,
  `OdometerIn` INT NULL,
  `LicenseVerified` TINYINT NOT NULL,
  `InsuranceVerified` TINYINT NOT NULL,
  PRIMARY KEY (`RentalID`),
  UNIQUE INDEX `ReservationID_UNIQUE` (`ReservationID` ASC) VISIBLE,
  CONSTRAINT `fk_rental_reservation`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `luxury_car_rental`.`RESERVATION` (`ReservationID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luxury_car_rental`.`PAYMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luxury_car_rental`.`PAYMENT` (
  `PaymentID` INT NOT NULL AUTO_INCREMENT,
  `ReservationID` INT NOT NULL,
  `PaymentDateTime` DATETIME NOT NULL,
  `Amount` DECIMAL(10,2) NOT NULL,
  `PaymentMethod` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`PaymentID`),
  INDEX `fk_payment_reservation_idx` (`ReservationID` ASC) VISIBLE,
  CONSTRAINT `fk_payment_reservation`
    FOREIGN KEY (`ReservationID`)
    REFERENCES `luxury_car_rental`.`RESERVATION` (`ReservationID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
